### ISSUE TITLE
???

### ISSUE THREAD

**Issue by dharxx** [leopic/makeAppIcon#2]
at ChildProcess.<anonymous> (/usr/local/lib/node_modules/makeappicon/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "image.png" this most likely means the gm/convert binaries can't be

**Comment by GabLeRoux** [comment]
This is a very bad issue title, You should rename to "gm/convert binaries can't be found".
Having same issue here on MacOs.

This basically means we're missing `gm/covert` binaries.

Here's a guide on how to install it:
http://stackoverflow.com/questions/17756587/installing-graphicsmagick-on-mac-os-x-10-8

This should be written in the ReadMe.md :octocat:

**Comment by leopic** [comment]
Hello!

My apologies dharxx I've neglected this repo as of late.

Thank you @GabLeRoux for jumping on this one, I'll make sure to add that into the project's README.

**Comment by leopic** [comment]
@dharxx please take a look at the updated README.md by @GabLeRoux, that should help clear some of the confusion

**Comment by leopic** [comment]
Closing this one.
